### ISSUE TITLE
invalid hashbang in init-cluster for some systems

### ISSUE THREAD

**Issue by ClaytonJY** [StevenACoffman/self-driving-kubernetes-on-aws#3]
`/usr/bin/env bash -ex` doesn't work for for me, but plain ol `/bin/bash -e` (as in `make-eks.sh`) does.

Should I file a PR for this? is the `-x` necessary?

**Comment by StevenACoffman** [comment]
Huh. I thought it would be the other way around. [env bash](https://unix.stackexchange.com/questions/206350/what-is-the-difference-if-i-start-bash-with-bin-bash-or-usr-bin-env-bash) is supposed to be more portable. Maybe the `-x` doesn't combine with it well? I moved it to have an explicit `set -x` to tell it to exit if there's an error. Please let me know if this works on your system (and what your system environment is if not).

**Comment by ClaytonJY** [comment]
Weirdly, I can't seem to reproduce the bad behavior in a fresh script, but I've also been reconfiguring my shell and other environment stuff so who knows. I can see you've moved the options off the shebang line, so I think this is all sorted!
